config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "reicos#index"
  resources :users, only: [:edit, :update]
  resources :refriges, only: [ :index, :new, :create, :edit, :update, :destroy] do
    resources :foods,:comments, only: [ :index, :new, :create, :edit, :update, :destroy] do
      collection  do
       get 'search'
      end
      collection  do
        get 'category'
       end
       collection  do
        get 'change'
       end
    end
  end
  get 'foods/:id', to: 'foods#checked'#特定のfoodテーブルを指定するためにid

end

app/models/comment.rb
class Comment < ApplicationRecord
  with_options presence: true do
    validates :text
    validates :refrige_id
    validates :user_id
  end

  belongs_to :user
  belongs_to :refriges, optional: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_refrige, only: [:index, :create]
  before_action :move_to_index
  def index
    @comment = Comment.new
    @comments = @refrige.comments.includes(:user).all.order(id: 'DESC')
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to refrige_comments_path
    else
      redirect_to refrige_comments_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, refrige_id: params[:refrige_id])
  end

  def set_refrige
    @refrige = Refrige.find(params[:refrige_id])
  end

  def move_to_index
    redirect_to root_path unless @refrige.user_ids.include? current_user.id
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<header class="header">
    <div class="inner">
      <div class="nav">
        <div class="left_bar">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
        </div>
        <div class="right_bar">
          <div class="menu__right"> 
             <%= link_to "食材追加", new_refrige_food_path, class: :menu__btn %>
          </div> 
          <div class="menu__right"> 
             <%= link_to "検索・編集", search_refrige_foods_path, class: :menu__btn %>
          </div>
          <div class="menu__right"> 
             <%= link_to "my reico",  refrige_foods_path, class: :menu__btn %>
          </div> 
        </div>
      </div>
    </div>
</header>
<div class="food-page">
  <div class="index-comment">
    <div class="comment_title">
      <div class="refrige_comment">
        <%= link_to @refrige.refrige_name, edit_refrige_path(@refrige.id) %>
      </div>
      <p class="text_comment">
        ■ 同じreicoを共有している仲間とチャットしよう ■
      </p>
    </div>
    <div class="comment_form">
      <%= form_with(model: [@refrige, @comment], local: true) do |f| %>
          <%= f.text_field :text , class: "comment_in", id:"comment_in", placeholder:"コメントを入力してください" %>
          <%= f.submit "送信する", class: "comment__btn", id:"comment__btn" %>
      <% end %> 
    </div>
    <div class="comment_field">
      <ul class="comments_lists">
        <% if @comments %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <div class="comment_up">
                <div class="comment_user">
                  <%= comment.user.nickname %>
                </div>
                <div class="comment_date">
                  <%= comment.created_at.strftime("%Y-%m-%d %H:%M") %>
                </div>
              </div>
              <div class="comment_text">
                <%= comment.text %>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>