config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "reicos#index"
  resources :users, only: [:edit, :update]
  resources :refriges, only: [ :index, :new, :create, :edit, :update, :destroy] do
    resources :foods,:comments, only: [ :index, :new, :create, :edit, :update, :destroy] do
      collection  do
       get 'search'
      end
      collection  do
        get 'category'
       end
       collection  do
        get 'change'
       end
    end
  end
  get 'foods/:id', to: 'foods#checked'#特定のfoodテーブルを指定するためにid

end

app/views/shared/_category.html.erb
<ul class="category_menu">
  <li><a class="category__btn">カテゴリー</a>
    <ul>
      <li><%= link_to "肉類",category_refrige_foods_path(category_id:2)%></li>
      <li><%= link_to "魚介類",category_refrige_foods_path(category_id:3)%></li>
      <li><%= link_to "乳製品類",category_refrige_foods_path(category_id:4)%></li>
      <li><%= link_to "卵類",category_refrige_foods_path(category_id:5)%></li>
      <li><%= link_to "きのこ・山菜類",category_refrige_foods_path(category_id:6)%></li>
      <li><%= link_to "野菜類",category_refrige_foods_path(category_id:7)%></li>
      <li><%= link_to "果物類",category_refrige_foods_path(category_id:8)%></li>
      <li><%= link_to "お惣菜類",category_refrige_foods_path(category_id:9)%></li>
      <li><%= link_to "豆・豆腐類",category_refrige_foods_path(category_id:10)%></li>
      <li><%= link_to "乾物・海藻類",category_refrige_foods_path(category_id:11)%></li>
      <li><%= link_to "ご飯類",category_refrige_foods_path(category_id:12)%></li>
      <li><%= link_to "パン類",category_refrige_foods_path(category_id:13)%></li>
      <li><%= link_to "麺類",category_refrige_foods_path(category_id:14)%></li>
      <li><%= link_to "調味料",category_refrige_foods_path(category_id:15)%></li>
      <li><%= link_to "乳飲料",category_refrige_foods_path(category_id:16)%></li>
      <li><%= link_to "お菓子",category_refrige_foods_path(category_id:17)%></li>
      <li><%= link_to "その他",category_refrige_foods_path(category_id:18)%></li>
    </ul>
  </li>
</ul>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.htmi.erb
  <%# CSS・・・assets/stylesheets/shared/footer.css %>
  <footer class="footer">
      <p class="copyright">Copyright  ITO All rights reserved.</p>
  </footer>

app/views/shared/_footer.html.erb
  <%# CSS・・・assets/stylesheets/shared/footer.css %>
  <footer class="footer">
      <p class="copyright">Copyright  ITO All rights reserved.</p>
  </footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class="header">
      <div class="inner">
        <div class="nav">
          <div class="left_bar">
            <div class="nav__left">
              <%= link_to image_tag("logo.png", class: :logo), root_path %>
            </div>
          </div>
               <%# ログインしているときは以下を表示するようにしましょう %>
          <div class="right_bar">
            <% if user_signed_in? %>
              <div class="nav__right">
                 <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
                 <%= link_to "My home", refriges_path, class: :nav__btn %>
              </div>
               <%# // ログインしているときは上記を表示するようにしましょう %>
              <% else %>
               <%# ログインしていないときは以下を表示するようにしましょう %>
              <div class="nav__right">
                <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
                <%= link_to "新規登録",  new_user_registration_path, class: :nav__btn %>
              </div>
               <%# // ログインしていないときは上記を表示するようにしましょう %>
            <% end %>
          </div>
        </div>
    </div>
</header>

app/views/shared/_sort.html.erb
<ul class="sort_menu">
  <li><a class="sort__btn">並び替え</a>
    <ul>
      <li><%= link_to "購入日 新しい" ,change_refrige_foods_path(change:"purchase_new")%></li>
      <li><%= link_to "購入日 古い",change_refrige_foods_path(change:"purchase_old")%></li>
      <li><%= link_to "賞味期限 近い",change_refrige_foods_path(change:"sell_old")%></li>
      <li><%= link_to "賞味期限 遠い",change_refrige_foods_path(change:"sell_new")%></li>
      <li><%= link_to "現在の在庫のみ",change_refrige_foods_path(change:"checked_false")%></li>
      <li><%= link_to "消費済のみ",change_refrige_foods_path(change:"checked_true")%></li>
    </ul>
  </li>
</ul>