config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "reicos#index"
  resources :users, only: [:edit, :update]
  resources :refriges, only: [ :index, :new, :create, :edit, :update, :destroy] do
    resources :foods,:comments, only: [ :index, :new, :create, :edit, :update, :destroy] do
      collection  do
       get 'search'
      end
      collection  do
        get 'category'
       end
       collection  do
        get 'change'
       end
    end
  end
  get 'foods/:id', to: 'foods#checked'#特定のfoodテーブルを指定するためにid

end

app/models/refrige.rb
class Refrige < ApplicationRecord
  validates :refrige_name, presence: true, uniqueness: { case_sensitive: false }

  has_many :refrige_users, dependent: :destroy
  has_many :users, through: :refrige_users, validate: false
  has_many :foods, dependent: :destroy # refrigeレコードが削除されたら、関するfoodやrefrige_usersのレコードも削除される。
  has_many :comments, dependent: :destroy
end

app/controllers/refriges_controller.rb
class RefrigesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_refrige, only: [:edit, :update, :destroy]
  def index
  end

  def new
    @refrige = Refrige.new
  end

  def create
    @refrige = Refrige.new(refrige_params)
    if @refrige.save
      redirect_to refriges_path
    else
      render :new
    end
  end

  def edit
    redirect_to action: :index unless @refrige.user_ids.include? current_user.id
  end

  def update
    if @refrige.update(refrige_params)
      redirect_to refrige_foods_path(@refrige.id)
    else
      render :edit
    end
  end

  def destroy
    # redirect_to refriges_path if @refrige.destroy
    # redirect_to action: :index unless @refrige.user_ids.include? current_user.id
    redirect_to refriges_path and return if @refrige.destroy
    redirect_to action: :index and return unless @refrige.user_ids.include? current_user.id
  end

  private

  def refrige_params
    params.require(:refrige).permit(:refrige_name, user_ids: [])
  end

  def set_refrige
    @refrige = Refrige.find(params[:id])
  end
end

app/views/refriges/edit.html.erb
<header class="header">
      <div class="inner">
        <div class="nav">
          <div class="left_bar">
            <div class="nav__left">
              <%= link_to image_tag("logo.png", class: :logo), root_path %>
            </div>
          </div>
          <div class="right_bar">
              <div class="nav__right"> 
                 <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
                 <%= link_to "My home", refriges_path, class: :nav__btn %>
              </div> 
          </div>
        </div>
    </div>
</header>

<div class="contents-row">
  <div class="container">
     <h2 class="new-sing">My reico update</h2>
     <p class="newreico-title">冷蔵庫 (reico) の編集</p>
     <%= form_with model: @refrige, id: 'new_user', class: 'new_user', local: true do |f| %> 
        <%= render 'shared/error_messages', model: f.object%>
        <%#エラーメッセージを表示させる記述が必要%>
        <div class="form-group">
          <div class="field">
            <label class="form-text">My reico name</label>
            <span class="indispensable">（必須）</span>
          </div>
          <%= f.text_field :refrige_name, class:"input-default", id:"refrige_name", placeholder:"例) ハナコreico", maxlength:"40" %>
        </div>

        <div class="form-group">
          <div class="field">
            <label class="form-text">メンバー(選択せずに１人からでも始められます)</label>
          </div>
          <div class="user-group">
           <%= f.collection_select(:user_ids, User.where.not(id: current_user.id), :id, :nickname, {:prompt => "reicoを共有するユーザーを選択してください"}, {:multiple => true}) %>
             <input name="refrige[user_ids][]" type="hidden" value=<%= current_user.id %>>
         </div>
        </div>
        <div class="actions">
          <%= f.submit "Update",class:"send" %>
          <%= link_to "Delete", refrige_path, method: :delete, class:"refrige_delete" %>
        </div>
     <% end %>
  </div>
</div>

app/views/refriges/index.html.erb
<header class="header">
    <div class="inner">
      <div class="nav">
        <div class="left_bar">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
        </div>
        <div class="right_bar">
          
        </div>
      </div>
    </div>
</header>



<div class="mainpage">

<%# <%= ここから画面left %> 
  <div class="page_left">
    <div class="sabu_left">
        <div class="name">
            <div class="name_left">
              <%= link_to current_user.nickname, edit_user_path(current_user) %>
            </div>
             <p class="name_end">の reico</p>
          </div>
            <%# <%= ここから冷蔵庫名 一覧 %> 
            <% current_user.refriges.each do |refrige| %>
              <div class="refrige__btn">
                <div class="refrige_name">
                  <%= link_to refrige.refrige_name, refrige_foods_path(refrige) %>
               </div>
             </div>
            <% end %>
        
            <%# <%= ここまで冷蔵庫名 一覧 %>
    </div>
  </div>
<%# <%= ここまで画面left %> 



<%# <%= ここから画面right %>
  <div class="page_right">
    <div class="sabu_right">
      <p class="sabu_refrige--title">
          ■冷蔵庫をクリックすると食材が一覧表示されます■
         </p>
     <%# <%= ここから食材一覧 %>
     <%# <%= ここまで食材一覧 %>
    </div>
  </div>
<%# <%= ここまで画面right %>

</div>

app/views/refriges/new.html.erb
<header class="header">
      <div class="inner">
        <div class="nav">
          <div class="left_bar">
            <div class="nav__left">
              <%= link_to image_tag("logo.png", class: :logo), root_path %>
            </div>
          </div>

           <div class="right_bar">
           </div>
        </div>
      </div>
</header>


<div class="contents-row">
  <div class="container">
     <h2 class="new-sing">My reico up</h2>
     <p class="newreico-title">あなたの冷蔵庫 (reico) を作りましょう！</p>
     <%= form_with model: @refrige,id: 'new_user', class: 'new_user', local: true do |f| %> 
        <%= render 'shared/error_messages', model: f.object%>
        <%#エラーメッセージを表示させる記述が必要%>
        <div class="form-group">
          <div class="field">
            <label for="refrige_name" class="form-text">My reico name</label>
            <span class="indispensable">（必須）</span>
          </div>
          <%= f.text_field :refrige_name, class:"input-default", id:"refrige_name", placeholder:"例) ハナコreico", maxlength:"40" %>
        </div>

        <div class="form-group">
          <div class="field">
            <label for="refrige_user_ids" class="form-text">メンバー</label>
            <span class="indispensable">(選択せずに一人からでも始められます)</span>
          </div>
          <div class="user-group">
           <%= f.collection_select(:user_ids, User.where.not(id: current_user.id), :id, :nickname, {:prompt => "reicoを共有するユーザーを選択してください"}, {:multiple => true}) %>
              <%# <select name="refrige[user_ids][]">複数名選択したい %>
              <%# <option value="">reicoに招待するユーザーを選択してください</option>
              <% User.where.not(id: current_user.id).each do |user| %>
                <%# <option value><%= user.id><%= user.nickname %>  <%#</option> %>
              <%# <% end %>
            <%# </select> %> 
             <input name="refrige[user_ids][]" type="hidden" value=<%= current_user.id %>>
         </div>
        </div>
        <div class="actions">
          <%= f.submit "Up",class:"send" %>
        </div>
     <% end %> 
  </div>
</div>