config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "reicos#index"
  resources :users, only: [:edit, :update]
  resources :refriges, only: [ :index, :new, :create, :edit, :update, :destroy] do
    resources :foods,:comments, only: [ :index, :new, :create, :edit, :update, :destroy] do
      collection  do
       get 'search'
      end
      collection  do
        get 'category'
       end
       collection  do
        get 'change'
       end
    end
  end
  get 'foods/:id', to: 'foods#checked'#特定のfoodテーブルを指定するためにid

end

app/models/food.rb
class Food < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions # 記述してmoduleを取り込む
  belongs_to :category
  # ActiveHashを用いて、belongs_toを設定する
  with_options presence: true do
    validates :food_name
    validates :purchase_date
    validates :sell_by
    validates :refrige_id
  end
  validates :category_id, numericality: { other_than: 1 } # ジャンルの選択が「--」の時は保存できないようにする
  validates :checked, inclusion: { in: [true, false] }

  belongs_to :refrige, validate: false

  def self.search(search)
    # クラス全体に検索をかけたいから、クラス全体で使えるクラスメソッドを使う
    if search != ''
      Food.where('food_name LIKE(?) OR product_name LIKE(?) OR shop LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Food.all
    end
  end

  def self.category(category_id)
    if category_id != ''
      Refrige.food.where(category_id: category_id)
    else
      Food.all
    end
  end

  def self.change(change)
    case change
    when 'purchase_new'
      Food.all.order(purchase_date: :DESC)
    when 'purchase_old'
      Food.all.order(purchase_date: :ASC)
    when 'sell_new'
      # return Food.where.not(sell_by: nil).order(sell_by: "DESC")賞味期限を書いてないものは含めたくない場合
      Food.order('sell_by IS NULL, sell_by DESC')
    when 'sell_old'
      Food.order('sell_by IS NULL, sell_by ASC')
    when 'checked_false'
      Food.where.not(checked: true)
    when 'checked_true'
      Food.where.not(checked: false)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: [:edit, :update, :destroy]
  before_action :set_refrige, only: [:index, :new, :search, :category, :change]

  def index
    @foods = @refrige.foods.all.order(id: 'DESC')
    redirect_to root_path unless @refrige.user_ids.include? current_user.id
  end

  def new
    @food = Food.new
    redirect_to root_path unless @refrige.user_ids.include? current_user.id
  end

  def create
    # (food_name: params[:food][:food_name],product_name: params[:food][:product_name],category_id: params[:food][:category_id],purchase_date: params[:food][:purchase_date],sell_by: params[:food][:sell_by],shop: params[:food][:shop], refrige_id: params[:refrige_id])
    food = Food.new(food_params)
    if food.valid? # バリデーションを通っていれば
      category = Category.find(food.category_id)
      food.save
    end
    render json: { food: food, category: category }
  end

  def edit
  end

  def update
    if @food.update(food_params)
      redirect_to search_refrige_foods_path
    else
      render :edit
    end
  end

  def destroy
    if @food.destroy
      redirect_to search_refrige_foods_path
    else
      render :edit
    end
  end

  def checked
    food = Food.find(params[:id]) # これをこの後、以下の記述に書き換えてる
    if food.checked
      food.update(checked: false)
    else
      food.update(checked: true)
    end
    item = Food.find(params[:id]) # 新しく書き換えたものを変数itemに入れる
    render json: { food: item } # foodという箱にitemを入れて渡す。
  end

  def search
    @foods = @refrige.foods.search(params[:keyword]).order(id: 'DESC')
    redirect_to root_path unless @refrige.user_ids.include? current_user.id
  end

  def category
    @foods = @refrige.foods.where(category_id: params[:category_id]).order(id: 'DESC')
    render :search
  end

  def change
    @foods = @refrige.foods.change(params[:change])
    render :search
  end

  private

  def food_params
    params.require(:food).permit(:food_name, :product_name, :category_id, :purchase_date, :sell_by, :shop).merge(refrige_id: params[:refrige_id], checked: false)
  end # 画面上で入力してない値をパラメーターに含めたいときはmergeを使うchecked: false

  def set_food
    @food = Food.find(params[:id])
  end

  def set_refrige
    @refrige = Refrige.find(params[:refrige_id])
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/edit.html.erb
<header class="header">
      <div class="inner">
        <div class="nav">
          <div class="left_bar">
            <div class="nav__left">
              <%= link_to image_tag("logo.png", class: :logo), root_path %>
            </div>
          </div>
            <div class="right_bar">
              <div class="menu__right"> 
                <%= link_to "検索・編集", search_refrige_foods_path, class: :menu__btn %>
              </div>
              <div class="menu__right">
                <%= link_to  "my reico",  refrige_foods_path, class: :menu__btn %>
              </div>
            </div>
        </div>
      </div>
</header>

<div class="food-page">
   <div class="new-food">
     <p class="new-food-title">
       ■食材を編集・削除できます■
     </p>
     <p class="new-foodsub-title">
       (※ 食材名、カテゴリー、購入日の入力は必須です)
     </p>
     <%= render 'shared/error_messages', model: @food%>
     <%#エラーメッセージを表示させる記述が必要%>
     <div class="food-spece">
        <%= form_with model: @food, url: refrige_food_path, local: true do |f|%>
        <table class="form-table">
          <thead>
            <tr>
              <th>食材名 (必須)</th>
              <th>商品名　</th>
              <th>カテゴリー (必須)</th>
              <th>購入日(必須)</th>
              <th>賞味期限</th>
              <th>購入店　</th>
           </tr>
          </thead>
          <tbody class="bulk-registration-field">
            <tr class="item">
              <td>
                <%= f.text_field :food_name, class: 'food_name_form'%>
              </td>
              <td>
                <%= f.text_field :product_name, class: 'product_name_form'%>
              </td>
              <td>
                <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:'category_id_form', id:"category_id"}) %>
              </td>
              <td>
                <%= f.date_field  :purchase_date, class: 'purchase_date_form'%>
              </td>
              <td>
                <%= f.date_field :sell_by, class: 'sell_by_form' %>
              </td>
              <td>
                <%= f.text_field :shop, class: 'shop_form'%>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    <div class="edit_actions">
      <%= f.submit 'Up date', class: 'edit-btn-primary' %>
      <%= link_to "Delete", refrige_food_path, method: :delete, class:"food_delete" %>
    </div>
      <% end %>
  </div>
</div>












<%# <div class="contents-row">
  <div class="container">
     <h2 class="new-sing">Food update</h2>
     <p class="newreico-title">食材を編集できます</p>
     <%= form_with model: @food,id: 'edit_food', class: 'edit_foo', local: true do |f| %> 
        <%# <%= render 'shared/error_messages', model: f.object%>
        <%#エラーメッセージを表示させる記述が必要%>
        <%# <div class="form-group">
          <div class="field">
            <label class="form-text">My reico name</label>
            <span class="indispensable">（必須）</span>
          </div>
          <%= f.text_area :refrige_name, class:"input-default", id:"refrige_name", placeholder:"例) ハナコreico", maxlength:"40" %>
        <%# </div>

        <div class="actions">
          <%= f.submit "Up",class:"send" %>
        <%# </div>
     <% end %> 
  <%# </div>
</div> %> 

app/views/foods/index.html.erb
<header class="header">
    <div class="inner">
      <div class="nav">
        <div class="left_bar">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
        </div>
        <div class="right_bar">
          <div class="menu__right"> 
             <%= link_to "食材追加", new_refrige_food_path, class: :menu__btn %>
          </div> 
          <div class="menu__right"> 
             <%= link_to "検索・編集", search_refrige_foods_path, class: :menu__btn %>
          </div>
          <div class="menu__right"> 
            <%= link_to "リクエスト", refrige_comments_path, class: :menu__btn %>
          </div>
        </div>
      </div>
    </div>
</header>

<div class="mainpage">
     <%# <%= ここから画面left %> 
    <div class="page_left">
       <div class="sabu_left">
            <%# <%= ここから冷蔵庫名 一覧 %> 
          <div class="name">
            <div class="name_left">
              <%= link_to current_user.nickname, edit_user_path(current_user) %>
            </div>
             <p class="name_end">の reico</p>
          </div>
          <% current_user.refriges.each do |refrige| %>
            <div class="refrige__btn">
              <div class="refrige_name">
                <%= link_to refrige.refrige_name, refrige_foods_path(refrige.id) %>
              </div>
            </div>
          <% end %>
            <%# <%= ここまで冷蔵庫名 一覧 %>
       </div>
    </div>
    <%# <%= ここまで画面left %> 

    <%# <%= ここから画面right %> 
  <div class="page_right">
    <div class="in_index">
     <%# <%= ここから食材一覧 %>
      <div class="index-food">
          <div class="refrige_right">
           <%= link_to @refrige.refrige_name, edit_refrige_path(@refrige.id) %>
          </div>
      </div>
      <div class="sabu_index_food">
        <div class="index_scroll">
          <table class="food_table">
            <th>食材名</th>
            <th>商品名</th>
            <th>カテゴリー</th>
            <th>購入日</th>
            <th>賞味期限</th>
            <th>購入店</th>
              <% @foods.each do |food| %>
                <tr class="food" data-id=<%= food.id %> data-check=<%= food.checked %>>
                  <td class="food_name" id="food" > <%= food.food_name %></td>
                  <td class="product_name" id="food"><%= food.product_name %></td>
                  <td class="category_id" id="food"><%= food.category.name %></td>
                  <td class="purchase_date" id="food"><%= food.purchase_date %></td>
                  <td class="sell_by" id="food"><%= food.sell_by %></td>
                  <td class="shop" id="food"><%= food.shop %></td>
                </tr>
              <% end %>
          </table>
        </div>
      </div>
      <%# <%= ここまで食材一覧 %> 
    </div>
  </div>
</div>
<%# <%= ここまで画面right %> 

app/views/foods/new.html.erb
<header class="header">
    <div class="inner">
      <div class="nav">
        <div class="left_bar">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
        </div>
        <div class="right_bar">
          <div class="menu__right"> 
             <%= link_to "my reico",  refrige_foods_path, class: :menu__btn %>
          </div> 
        </div>
      </div>
    </div>
</header>

<div class="food-page">
   <div class="new-food">
     <p class="new-food-title">
       ■購入食材を冷蔵庫に追加しよう■
     </p>
     <p class="new-foodsub-title">
       (※ 食材名・カテゴリー・購入日・賞味期限 の入力は必須です)
     </p>
     <div  class="food-spece">
       <%= form_with model: [@refrige, @food], url: refrige_foods_path, method: :post,id: "form" do |f|%>
        <%#エラーメッセージを表示させる記述が必要 Ajaxなのでアラートでエラーメッセージ表示%>
       <table class="form-table">
         <thead>
           <tr>
             <th>食材名 (必須)</th>
             <th>商品名　</th>
             <th>カテゴリー (必須)</th>
             <th>購入日(必須)</th>
             <th>賞味期限(必須)</th>
             <th>購入店　</th>
           </tr>
         </thead>
        <tbody class="bulk-registration-field">
          <tr class="item" data-id=<%= @refrige.id%> id=new_food  data-check=<%= @food.checked %>>
            <td>
              <%= f.text_field :food_name, id: "food_name", class: 'food_name_form'%>
            </td>
            <td>
              <%= f.text_field :product_name, id: "product_name", class: 'product_name_form'%>
            </td>
            <td>
              <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:'category_id_form', id:"category_id"}) %>
            </td>
            <td>
              <%= f.date_field  :purchase_date, id: "purchase_date", class: 'purchase_date_form'%>
            </td>
            <td>
              <%= f.date_field :sell_by, id: "sell_by", class: 'sell_by_form' %>
            </td>
            <td>
              <%= f.text_field :shop, id: "shop", class: 'shop_form'%>
            </td>
          </tr>
      </tbody>
    </table>
    </div>
    <div class="text-center">
      <%= f.submit '食材を追加', class: 'btn-btn-primary',id: "food_submit" %>
    </div>
    <% end %>
    <div class="java_food">
      <div id="list">
      </div>
    </div>
  </div>
</div>

app/views/foods/search.html.erb
<header class="header">
    <div class="inner">
      <div class="nav">
        <div class="left_bar">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
        </div>
        <div class="right_search_bar">
           <div class="menu__search">
             <%= form_with(url: search_refrige_foods_path, local: true, method: :get, class: "search-form") do |form| %>
             <%= form.text_field :keyword, placeholder: "食材を検索する", class: "search-input" %>
             <%= form.submit "検索", class: "search-btn" %>
             <% end %>
           </div>
           <div class="right__search"> 
             <%= link_to "my reico",  refrige_foods_path, class: :menu__btn %>
           </div>
        </div>
      </div>
    </div>
</header>

<div class="food-page">
   <div class="in_search">
     <div class="search-food">
       <div class="search-food-title">
         <div class="refrige_right">
        <%= link_to @refrige.refrige_name, edit_refrige_path(@refrige.id) %>
         </div>
         <p class="sabu-search-title">
          ■ Editをクリックすると食材の 編集・削除 ができます ■
         </p>
       </div>
       <div class="sub_search">
        <div class="category__search">
          <%= render "shared/category"%>
        </div>
        <div class="sort__search">
          <%= render "shared/sort"%>
        </div>
       </div>
     </div>
      <div class="sabu_food">
         <div class="food_scroll">
          <table class="food_table">
            <tr>
            <th>食材名</th>
            <th>商品名</th>
            <th>カテゴリー</th>
            <th>購入日</th>
            <th>賞味期限</th>
            <th>購入店</th>
            <th></th>
            </tr>
            <% @foods.each do |food| %>
              <tr class="foods" data-id=<%= food.id %> data-check=<%= food.checked %>>
                <td class="food_name" id="lists" > <%= food.food_name %></td>
                <td class="product_name" id="lists"><%= food.product_name %></td>
                <td class="category_id" id="lists"><%= food.category.name %></td>
                <td class="purchase_date" id="lists"><%= food.purchase_date %></td>
                <td class="sell_by" id="lists"><%= food.sell_by %></td>
                <td class="shop" id="lists"><%= food.shop %></td>
                <td class=edit_btn><%= link_to 'Edit', edit_refrige_food_path(id: food.id) %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
   </div>
</div>